config/routes.rb
Rails.application.routes.draw do
  resources :polls do
    get :public, on: :collection
    post :answer, on: :member
  end
  root to: 'polls#public'
  devise_for :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :option
  belongs_to :user

  validates :option_id, presence: true
  validates :ip, presence: true, uniqueness: { scope: :option_id }
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :poll
  has_many :answers, dependent: :destroy
  
  validates :name, presence: true, uniqueness: { scope: :poll_id }
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :user
  has_many :options, dependent: :destroy
  has_many :answers, through: :options

  validates :question, presence: true
  #validates :options, presence: true

  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true

  scope :opened, -> {where(public: true)}

  before_create :generate_uniq_token

  def answers_by(user, ip)
    Answer.where(
      <<-SQL
        option_id IN (SELECT id FROM options WHERE poll_id = #{self.id})
        AND (ip = inet '#{ip}' #{"OR user_id = #{user.id}" if user})
      SQL
    )
  end

  private

    def generate_uniq_token
      return if self.token.present?
      digest = loop do
        temp = SecureRandom.urlsafe_base64(nil, false).first(6)
        break temp unless self.class.exists?(token: temp)
      end
      self.token = digest
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :polls

  validates :email, presence: true, email: true
  
  protected
  
  def confirmation_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!, except: [:public, :show, :answer]
  before_action :set_poll, only: [:edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def public
    @polls = Poll.opened.order(id: :desc)
  end

  # GET /polls
  # GET /polls.json
  def index
    @polls = current_user.polls.order(id: :desc)
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find_by_token(params[:id])
  end

  # GET /polls/new
  def new
    @poll = current_user.polls.new
    @poll.options.build
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = current_user.polls.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to polls_url, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to polls_url, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answer
    @poll = Poll.find_by_token(params[:id])
    @poll.options.where(id: params[:answer]).each do |option|
      option.answers << Answer.create({
        user_id: current_user.try(:id),
        ip: request.remote_ip
      })
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = current_user.polls.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:user_id, :question, :token, :multi, :public, 
        options_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def broadcast(channel, &block)
    unless Rails.env.test?
      puts "Published to #{channel}"
      uri = URI.parse("http://localhost:9292/faye")
      Net::HTTP.post_form(uri, message: {
        channel: channel,
        data: capture(&block),
        ext: {
          auth_token: FAYE_TOKEN
        }
      }.to_json)
    end
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to 'Polls management', polls_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to 'Edit account', edit_user_registration_path
          %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          %li= link_to 'Sign in', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Voting'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Voting'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    :javascript
      window.fayeHost = '#{FAYE_HOST}'
    %script{src: "//#{FAYE_HOST}/faye.js"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .wrap
      %header
        = render 'layouts/navigation'
      .container
        = render 'layouts/messages'
        = yield
    .footer
      .text-center
        Developed by:
        = link_to 'Viktor Oleksyn', 'http://ua.linkedin.com/in/bartezic/en', target: :_blank

app/views/polls/_form.html.haml
.panel.panel-default
  = simple_form_for(@poll) do |f|
    = f.error_notification

    .panel-body.form-inputs
      = f.input :question, label: false, placeholder: 'Question'
      #options
        = f.simple_fields_for :options do |option|
          = render 'option_fields', f: option
        .links
          = link_to_add_association f, :options do
            %button.btn.btn-default
              %span.glyphicon.glyphicon-plus-sign
              Add answer
      = f.input :multi
      = f.input :public
    .panel-footer.form-actions
      = f.button :submit

app/views/polls/_option_fields.html.haml
.nested-fields.row
  .col-xs-1
    = link_to_remove_association f, {} do
      %button.btn.btn-default
        %span.glyphicon.glyphicon-remove-sign
  .col-xs-11
    = f.input :name, label: false, placeholder: 'Answer...'

app/views/polls/_poll.html.haml
- if (answers = poll.answers_by(current_user, request.remote_ip)).size > 0
  - max = poll.answers.count
  - poll.options.each do |option|
    - now = option.answers.count
    = option.name
    .progress
      .progress-bar.progress-bar-success.progress-bar-striped{role: :progressbar, 'aria-valuenow': now, 'aria-valuemin': "0", 'aria-valuemax': max, style: "width: #{now.to_f/max.to_f*100.0}%"}
        #{now} of #{max}
- else
  = form_tag(answer_poll_path(poll.token), method: :post, remote: true) do
    - poll.options.each do |option|
      %label
        %input{type: (poll.multi ? :checkbox : :radio), name: "answer[]", value: option.id}
        = option.name
      %br
    = submit_tag 'Vote', class: 'btn btn-xs btn-success'

app/views/polls/answer.js.haml
$(".panel-body[data-poll-id=#{@poll.token}]").html("#{escape_javascript(render 'poll', poll: @poll)}");
- broadcast '/answers' do
  $(".panel-body[data-poll-id=#{@poll.token}]").html("#{escape_javascript(render 'poll', poll: @poll)}");

app/views/polls/edit.html.haml
.row
  .col-sm-6.col-sm-offset-3
    %h1 Editing poll

    = render 'form'

app/views/polls/index.html.haml
%h1
  Polls management
  .pull-right
    = link_to new_poll_path, class: 'btn btn-default' do
      %span.glyphicon.glyphicon-plus-sign
      New Poll
  .clearfix

- @polls.each do |poll|
  .panel.panel-default
    .panel-heading
      %h2.panel-title.pull-left= poll.question
      .pull-right
        %span.label.label-default Multi: #{poll.multi}
        %span.label.label-default Public: #{poll.public}
        %span.label.label-default created by: #{poll.user.name}
        %span.label.label-default created at: #{l(poll.created_at, format: :full)}
      .clearfix
    .panel-body{data:{poll: {id: poll.token}}}
      = render 'poll', poll: poll
    .panel-footer
      .pull-right
        %button.btn.btn-default{type: :button, title: 'Share poll link', data: {toggle: :popover, content: poll_url(poll.token), placement: :top}}
          %span.glyphicon.glyphicon-link
        = link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default'
        = link_to 'Destroy', poll, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
      .clearfix

.pull-right
  = link_to new_poll_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-plus-sign
    New Poll
.clearfix

app/views/polls/new.html.haml
.row
  .col-sm-6.col-sm-offset-3
    %h1 New poll

    = render 'form'

app/views/polls/public.html.haml
%h1 Public polls 

- @polls.each do |poll|
  .panel.panel-default
    .panel-heading
      %h3.panel-title.pull-left= poll.question
      .pull-right
        %span.label.label-default created by: #{poll.user.name}
      .clearfix
    .panel-body{data:{poll: {id: poll.token}}}
      = render 'poll', poll: poll

app/views/polls/show.html.haml
%h1 Poll

.panel.panel-default
  .panel-heading
    %h3.panel-title.pull-left= @poll.question
    .pull-right
      %span.label.label-default created by: #{@poll.user.name}
    .clearfix
  .panel-body{data:{poll: {id: @poll.token}}}
    = render 'poll', poll: @poll